class RealtimeEvents {
  const RealtimeEvents._();

  static const knownBackendEvents = <String>[
    'WorkspacePresenceChanged',
    'PagePresenceChanged',
    'PageCursorChanged',
    'PageMousePointerChanged',
    'PageCreated',
    'PageUpdated',
    'PageDeleted',
    'BlockCreated',
    'BlockUpdated',
    'BlockDeleted',
    'BlockDraftChanged',
    'BlockEditingStateChanged',
    'BlockLeaseChanged',
    'TaskCreated',
    'TaskUpdated',
    'TaskDeleted',
    'TaskAssigned',
    'TaskUnassigned',
    'TaskStatusChanged',
    'TaskAssignedFromRecommendation',
    'TaskCompletedFromRecommendation',
    'TaskCommentCreated',
    'TaskCommentUpdated',
    'TaskCommentDeleted',
    'TaskCommentRestored',
    'NotificationCreated',
    'NotificationReadChanged',
    'NotificationUnreadCountChanged',
    'RecommendationCreated',
    'FriendRequestReceived',
    'FriendRequestSent',
    'FriendRequestAccepted',
    'FriendRequestRejected',
    'FriendRequestCancelled',
    'FriendshipChanged',
    'FriendRemoved',
    'ConversationUpserted',
    'MessageCreated',
    'ConversationRead',
    'ConversationTyping',
  ];
}
